name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    container:
      image: byivo/mdc-php-checker:foo-bar
      volumes:
        - foo-bar:/opt/project
    
    runs-on: ubuntu-latest

    steps:
    - name: Check if all exercises were solved correctly
      run: echo 'Test'
      
