name: Check exercises

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    container:
      image: byivo/mdc-php-checker:foo-bar
      volumes:
        - foo-bar:/opt/project
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Check if all exercises were solved correctly
        run: vendor/bin/phpunit
      
