name: Check if all exercises were properly solved

on:
  pull_request:
    branches:
    - master

jobs:
  checking-solutions:
    name: Checking ${{ matrix.exercise }} solution
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        exercise: [atm, count-a, calculator, superglobal, ddos-tracker, palindrome, trouble-array, fibonacci, variables, fizz-buzz, pimp-my-log, secret-salt, error-in-try]
    steps:
      - name: Checkout ${{ github.actor }} code
        uses: actions/checkout@master

      - name: Pulling ${{ matrix.exercise }} docker image
        run: docker pull byivo/mdc-php-checker:${{ matrix.exercise }}

      - name: Running ${{ matrix.exercise }} tests against proposed solution
        run: docker run -v $(pwd)/${{ matrix.exercise }}:/opt/project/public byivo/mdc-php-checker:${{ matrix.exercise }}
